### ISSUE TITLE
Question: s3 ownership

### ISSUE THREAD

**Issue by random-robbie** [bbb31/slurp#1]
Just want to check that when you do ./slurp domain --domain example.com

is this then checking the SSL Certs for the domain and then doing permutations to find the buckets?

reason i ask is i want to ensure if i report a bucket it is that company that owns it.

**Comment by bbb31** [comment]
When you run manually it does not use certstream at all; the underlying code is the same, but the way it gets the data (you gave it to it in the call to `domain --domain example.com`) is different.

In manual mode:
1. Creates the permutations based on what you supplied to it, for example: `example.com`
2. Then sends requests to amazon with the permutations; something like: `curl -H "Host: <permutation>" http://s3-1-w.amazonaws.com`; depending on the response you'll see either the `FORBIDDEN` or `PUBLIC` messages.

**Comment by random-robbie** [comment]
ok so there is no real way to tell who owns that bucket if it comes back as public listed.

Just wanted to double check on that before i fire some reports in.

I will have to double check the content of the bucket before hand.

**Comment by bbb31** [comment]
Do you mean like a user name to an aws account?

If you want to know how to find out who owns the domain you're going to need to use `whois` tools; ie `whois example.com`

**Comment by random-robbie** [comment]
ok so say i do uber.com...

I see next to it the domain 
<img width="551" alt="screen shot 2017-12-03 at 23 16 15" src="https://user-images.githubusercontent.com/4902869/33531052-04f915be-d880-11e7-9215-37261ca78bdd.png">

i presume now that the permutations is just returning what valid buckets it found but not confirming it belongs to that domain.

**Comment by bbb31** [comment]
There is no way to confirm 100% that each domain belongs to the respective bucket. AWS and S3 are completely independent services of DNS.
