### ISSUE TITLE
permutations..

### ISSUE THREAD

**Issue by random-robbie** [bbb31/slurp#13]
hey dude,

I've submitted a massive list to https://github.com/tomdev/teh_s3_bucketeers/blob/master/common_bucket_prefixes.txt which may help with permutations.

alot of my submissions to this list have been from buckets found in the wild or from bounty programs so this should help find more.

**Comment by bbb31** [comment]
Please send a PR

**Comment by bbb31** [comment]
Also note that if you send a PR @eur0pa sent in quite a bit of permutations (thanks again!) please confirm that you do not add any duplicates.
