### ISSUE TITLE
Errors build & install process

### ISSUE THREAD

**Issue by emanuelecesari** [bbb31/slurp#3]
Could you please explain me how make this script works?
I tryed **go build** but i am getting this errors:
```
main.go:32:2: cannot find package "github.com/CaliDog/certstream-go" in any of:
	/usr/lib/go-1.8/src/github.com/CaliDog/certstream-go (from $GOROOT)
	/home/lele/go/src/github.com/CaliDog/certstream-go (from $GOPATH)
main.go:36:2: cannot find package "github.com/Sirupsen/logrus" in any of:
	/usr/lib/go-1.8/src/github.com/Sirupsen/logrus (from $GOROOT)
	/home/lele/go/src/github.com/Sirupsen/logrus (from $GOPATH)
main.go:37:2: cannot find package "github.com/Workiva/go-datastructures/queue" in any of:
	/usr/lib/go-1.8/src/github.com/Workiva/go-datastructures/queue (from $GOROOT)
	/home/lele/go/src/github.com/Workiva/go-datastructures/queue (from $GOPATH)
main.go:33:2: cannot find package "github.com/jmoiron/jsonq" in any of:
	/usr/lib/go-1.8/src/github.com/jmoiron/jsonq (from $GOROOT)
	/home/lele/go/src/github.com/jmoiron/jsonq (from $GOPATH)
main.go:34:2: cannot find package "github.com/joeguo/tldextract" in any of:
	/usr/lib/go-1.8/src/github.com/joeguo/tldextract (from $GOROOT)
	/home/lele/go/src/github.com/joeguo/tldextract (from $GOPATH)
main.go:30:2: cannot find package "github.com/spf13/cobra" in any of:
	/usr/lib/go-1.8/src/github.com/spf13/cobra (from $GOROOT)
	/home/lele/go/src/github.com/spf13/cobra (from $GOPATH)
```
I tryed to clone these repository into the slurp folder but it dosent works
Could you help me?

**Comment by jubabaghdad** [comment]
I tried to install it, but got the same error as mentioned above, I will appreciate if the author create a video tutorial for the correct method to install it

thnx

**Comment by Os3r3um** [comment]
@jubabaghdad Until that point you can use the releases compiled version.

**Comment by ralphutz** [comment]
I've tried to compile and use the releases on all 3 available OSs and they all error with "INFO[0000] Check Help]"  This is when trying to "go build" and with the included script and just executing the precompiled release.

**Comment by bbb31** [comment]
Make sure that you clone into your `$GOPATH`.

**Comment by jmccorm** [comment]
I got around it with go get github.com/bbb31/slurp but then I ran into additional errors in gorilla's github project that I had to resolve by upgrading the version of Go.
