### ISSUE TITLE
Requires permutations.json to be in the current working directory

### ISSUE THREAD

**Issue by jmccorm** [bbb31/slurp#4]
I thought you might consider a better way than having us hard-code the path or otherwise guarantee permutations.json will be in our current working directory.

pi@raspberrypi:/tmp $ /home/pi/go/bin/slurp certstream
INFO[0000] Initializing....
INFO[0000] Starting to stream certs....
INFO[0000] Starting to process queue....
INFO[0000] Starting to process permutations....
FATA[0006] open ./permutations.json: no such file or directory
pi@raspberrypi:/tmp $

**Comment by bbb31** [comment]
Should be easy enough to implement with `os.Stat` and `spf13/cobra`. I'll be busy the next two weeks; don't really have time to add feature enhancements. I will however make time if there are any bugs.

**Comment by lukerodham** [comment]
hey, just implemented this myself, created a PR https://github.com/bbb31/slurp/pull/6

**Comment by bbb31** [comment]
See #6
