### ISSUE TITLE
Packages for Raspberry Pi contain Go 1.3, which is too low

### ISSUE THREAD

**Issue by jmccorm** [bbb31/slurp#5]
I ended up following the instructions here, which worked around my install issues:
https://gist.github.com/konradko/a9468beb70f0fa47766f5ebf966f24e8

**Comment by bbb31** [comment]
I use the latest version of go (1.9.x); using anything less than that your mileage may vary.

**Comment by bbb31** [comment]
I'm going to close this because this is technically an issue with the raspberry pi (I cant control what version of go is distributed with it).
