### ISSUE TITLE
Feature request - Internationalized domain name support

### ISSUE THREAD

**Issue by crypticgeek** [bbb31/slurp#7]
Request to support Internationalized domain name. These are domains with unicode characters. See more at https://en.wikipedia.org/wiki/Internationalized_domain_name

Currently an error is received when attempting to check an IDN.

```
$ ./slurp-linux-amd64 domain --domain δπθ.gr
FATA[0000] Is the domain even valid bruh?
```

As a workaround you can check the punycode version, not sure if this is even a valid thing to look for on S3 though.

```
$ ./slurp-linux-amd64 domain --domain xn--pxaix.gr
INFO[0000] Starting to process permutations....
```

I don't know how or if these come across from the cert stream or not, I haven't seen one I don't think.

**Comment by bbb31** [comment]
I was thinking about this yesterday actually but didn't get around to testing it.

**Comment by bbb31** [comment]
See 1.4
